name: Update GitHub Profile README
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *' # Run every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update GitHub Profile README
        uses: Chell0/github-update-readme@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
