name: Update GitHub Stats
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"


jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Stats
        uses: lowlighter/metrics@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Chell0
          config: .github/metrics.yml
